# Generated by Django 3.0.2 on 2020-01-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=128, verbose_name='学号')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('age', models.CharField(max_length=128, verbose_name='年龄')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu', models.ManyToManyField(to='app.Students')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app.UserProfile'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=128, verbose_name='课程名')),
                ('stu', models.ManyToManyField(to='app.Students')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Teachers')),
            ],
        ),
    ]
